### ISSUE TITLE
Controls

### ISSUE THREAD

**Issue by Maris701** [homelessbread/giant-floating-baby-head#10]
I would like to be able to change the controls to summon the floating image.

**Comment by homelessbread** [comment]
Thanks for the suggestion!  I'll look into adding a way to do that.

**Comment by homelessbread** [comment]
I've implemented the ability to configure the keyboard shortcut which summons the floating image and I've submitted the update (0.10) to the Chrome Web Store.
By default the shortcut is Ctrl+Shift+F, however, if you go to your _chrome://extensions_ page then at the bottom click on the _Keyboard Shortcuts_ link.  You'll see the _Show Giant Floating Baby Head_ shortcut that you can then update it to whatever you want it to be!

Thanks again for the suggestion!  Sorry I took so long to implement it.

**Comment by homelessbread** [comment]
![keyboard_shortcut_setting](https://user-images.githubusercontent.com/2532819/28237219-8cc51a18-68f7-11e7-9ea0-d6248dc05bea.JPG)
