### ISSUE TITLE
Disable on certain websites

### ISSUE THREAD

**Issue by tannorolsen** [homelessbread/giant-floating-baby-head#15]
I love the extension, but would it be possible to set certain websites that it doesnt appear on, such as Netflix?

**Comment by homelessbread** [comment]
Thanks @tannorolsen, that's a good idea. I'll  work on adding that in.

**Comment by homelessbread** [comment]
@tannorolsen, I pushed an update to the store with this new setting. It should show up after Chrome automatically updates your extension to version 0.12.

Thanks for the suggestion!
