### ISSUE TITLE
the image field is not working

### ISSUE THREAD

**Issue by 18mann** [homelessbread/giant-floating-baby-head#8]
![screenshot 2016-09-02 at 9 09 27 am](https://cloud.githubusercontent.com/assets/10088124/18204860/fdc544ee-70ec-11e6-8632-0f96049a765a.png)

**Comment by homelessbread** [comment]
Thanks for trying the extension!
What exactly is not working with the image field?  Are you not able to save a URL?  Is the image not appearing?

**Comment by 18mann** [comment]
it says unable to load the image beside the url box heres a screen shot
![blue owl](https://cloud.githubusercontent.com/assets/10088124/18273513/9b5b84a4-740b-11e6-8616-3ee24a3ff73e.png)
